FROM node:18-alpine

WORKDIR /FinanceTrack/finance_track_frontend/

COPY ./ ./
# COPY package.json /FinanceTrack/investViewfinance_track_frontend_frontend/
# COPY package-lock.json /FinanceTrack/finance_track_frontend/
RUN npm install

# COPY ./ /FinanceTrack/finance_track_frontend/