FROM node:18-alpine

WORKDIR /FinanceTrack/finance_track_frontend/

COPY ./ ./

RUN npm install
#
#COPY ./finance_track_frontend/ ./
#
RUN npm run build

# COPY ./ ./FinanceTrack/finance_track_frontend/