# FROM node:18-alpine

# WORKDIR /FinanceTrack/finance_track_frontend/

# COPY ./ ./

# RUN npm install
# #
# #COPY ./finance_track_frontend/ ./
# #
# RUN npm run build

# # COPY ./ ./FinanceTrack/finance_track_frontend/

###########
# BUILDER #
###########
FROM node:18-alpine as builder

COPY package*.json ./
RUN npm install --force
RUN mkdir /finance_track_frontend
RUN mv ./node_modules ./finance_track_frontend

WORKDIR /finance_track_frontend
COPY . .

RUN npm run build

#########
# FINAL #
#########
FROM nginx:alpine
COPY --from=builder /finance_track_frontend/build /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
