version: '3.7'

services:
  backend-prod:
    build:
      context: ./finance_track_backend
      dockerfile: Dockerfile-prod
    container_name: "finance-track-backend-prod"
    command: gunicorn FinanceTrack.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/finance_track_backend/api/static
    networks:
      - prod
    expose:
      - 8000
    env_file:
      - ./finance_track_backend/.env.prod
    depends_on:
      - db-prod

  frontend-prod:
    build:
      context: ./finance_track_frontend
      dockerfile: Dockerfile-prod
    container_name: "finance-track-frontend-prod"
    volumes:
      - static_volume:/home/app/finance_track_backend/api/static
    env_file:
      - ./finance_track_frontend/.env.production
    networks:
      - prod
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_URL=localhost
    depends_on:
      - "backend-prod"

  db-prod:
    image: postgres:13.2-alpine
    container_name: "finance-track-db-prod"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - prod
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data_prod:
  static_volume:

networks:
  prod:
