version: '3.3'

services:
  backend:
    build:
      context: ./finance_track_backend
      dockerfile: ./Dockerfile-prod
    command: >
      sh entrypoint.sh
      gunicorn FinanceTrack.wsgi:application -b 0.0.0.0:8000
    volumes:
      - ./finance_track_backend:/FinanceTrack/finance_track_backend/
    ports:
      - 8000:8000
    env_file:
      - ./finance_track_backend/.env.prod
    stdin_open: true
    depends_on:
      - db
  frontend:
    build:
      context: ./finance_track_frontend
      dockerfile: ./Dockerfile-prod
    command: >
      sh -c "npm run start --poll"
    volumes:
      - ./finance_track_frontend/src/:/FinanceTrack/finance_track_frontend/src/
      - ./finance_track_frontend/public/:/FinanceTrack/finance_track_frontend/public/
      - ./finance_track_frontend/build/:/FinanceTrack/finance_track_frontend/build/
#    expose:
#      - 3000
#    ports:
#      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
    depends_on:
      - backend
      - db
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./finance_track_backend/.env.prod
#    environment:
#      - POSTGRES_USER=0xN1ck
#      - POSTGRES_PASSWORD=FinTrackPasOne99Seven
#      - POSTGRES_DB=FinanceTrackProd
    ports:
      - 5432:5432
    restart: unless-stopped
volumes:
  postgres_data: