version: '3.7'

services:
  backend:
    build: ./finance_track_backend
    command: >
      sh entrypoint.sh
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./finance_track_backend:/FinanceTrack/finance_track_backend/
    ports:
      - 8000:8000
    env_file:
      - ./finance_track_backend/.env.dev
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
    depends_on:
      - db
  frontend:
    build: ./finance_track_frontend
    command: >
      sh -c "npm run start --poll"
    volumes:
    - ./finance_track_frontend/src/:/FinanceTrack/finance_track_frontend/src/
    - ./finance_track_frontend/public/:/FinanceTrack/finance_track_frontend/public/
    ports:
    - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
    depends_on:
      - backend
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=0xN1ck
      - POSTGRES_PASSWORD=FinTrackPasOne99Seven
      - POSTGRES_DB=FinanceTrackDev
    ports:
    - 5432:5432
volumes:
  postgres_data: