version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/FinanceTrack/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=0xN1ck
      - POSTGRES_PASSWORD=FinTrackPasOne99Seven
      - POSTGRES_DB=FinanceTrackDev
volumes:
  postgres_data: