###########
# BUILDER #
###########
FROM python:3.10-alpine as builder

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev libffi-dev

RUN pip install --upgrade pip
COPY . .

# install dependencies
COPY ./requirements.txt ./requirements.txt
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements.txt

#########
# FINAL #
#########
FROM python:3.10-alpine

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev libffi-dev shadow

RUN useradd -ms /bin/sh app

ENV HOME=/home/app
ENV APP_HOME=/home/app/finance_track_backend
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/api
RUN mkdir $APP_HOME/api/static
WORKDIR $APP_HOME

COPY --from=builder /usr/src/app/wheels /wheels
COPY --from=builder /usr/src/app/requirements.txt .
RUN pip install --no-cache /wheels/*

COPY ./entrypoint-prod.sh $APP_HOME

COPY . $APP_HOME

RUN chmod +x ./entrypoint-prod.sh

RUN chown -R app:app $APP_HOME

USER app

ENTRYPOINT ["/bin/sh", "/home/app/finance_track_backend/entrypoint-prod.sh"]
